{
 "title": "Rivian R1T",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Mileage",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "lengthmi" } },
   "targets": [
    {
     "alias": "Odometer",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mi",
     "query": "SELECT max(\"value\") FROM \"mi\" WHERE (\"entity_id\" = 'r1t_odometer') AND $timeFilter GROUP BY time($__interval) fill(previous)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id::tag", "operator": "=", "value": "r1t_odometer" }
     ]
    }
   ]
  },
  {
   "title": "Odometer",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "lengthmi" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT mean(\"value\") FROM \"mi\" WHERE (\"entity_id\"::tag = 'r1t_odometer') AND $timeFilter GROUP BY time($__interval) fill(null)\n"
    }
   ]
  },
  {
   "title": "Average Miles Per Day Since Delivery",
   "type": "stat",
   "description": "Divides current odometer reading by the number of days since June 27th, 2024 (epoch 1719446400000)\n\nColor thresholds:\n\n\t•\tGreen (On Track): <= 27.4\n\t•\tYellow (Caution): 27.5 - 30.0\n\t•\tRed (Over Limit): > 30.0",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "lengthmi" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT last(\"value\") \nFROM \"mi\" \nWHERE (\"entity_id\" = 'r1t_odometer') AND $timeFilter"
    }
   ]
  },
  {
   "title": "Estimated Range (Current)",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "lengthmi" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Est Range",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "mi",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id::tag", "operator": "=", "value": "r1t_estimated_vehicle_range" }
     ]
    }
   ]
  },
  {
   "title": "State of Charge (Current)",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "State of Charge",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "%",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id::tag", "operator": "=", "value": "r1t_battery_state_of_charge" }
     ]
    }
   ]
  },
  {
   "title": "Estimated Range",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "lengthmi" } },
   "targets": [
    {
     "alias": "Est Range",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "mi",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id::tag", "operator": "=", "value": "r1t_estimated_vehicle_range" }
     ]
    }
   ]
  },
  {
   "title": "State of Charge",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 10, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "State of Charge",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "%",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id::tag", "operator": "=", "value": "r1t_battery_state_of_charge" }
     ]
    }
   ]
  },
  {
   "title": "Altitude vs Est Range",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "lengthft" } },
   "targets": [
    {
     "alias": "Altitude",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ft",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id::tag", "operator": "=", "value": "r1t_altitude" }
     ]
    },
    {
     "alias": "Est Range",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mi",
     "query": "SELECT mean(\"value\") FROM \"autogen\".\"%\" WHERE (\"entity_id\"::tag = 'r1t_estimated_vehicle_range') AND $timeFilter GROUP BY time($__interval) fill(null)\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id::tag", "operator": "=", "value": "r1t_estimated_vehicle_range" }
     ]
    },
    {
     "alias": "Odometer",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mi",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id::tag", "operator": "=", "value": "r1t_odometer" }
     ]
    }
   ]
  },
  {
   "title": "Min Altitude",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "lengthft" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Altitude (ft)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ft",
     "query": "SELECT min(\"value\") FROM \"autogen\".\"ft\" WHERE (\"entity_id\"::tag = 'r1t_altitude')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id::tag", "operator": "=", "value": "r1t_altitude" }
     ]
    }
   ]
  },
  {
   "title": "Altitude",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "lengthft" } },
   "targets": [
    {
     "alias": "Altitude (ft)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ft",
     "query": "SELECT max(\"value\") FROM \"autogen\".\"ft\" WHERE (\"entity_id\"::tag = 'r1t_altitude') AND $timeFilter GROUP BY time($__interval) fill(previous)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id::tag", "operator": "=", "value": "r1t_altitude" }
     ]
    }
   ]
  },
  {
   "title": "Max Altitude",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "lengthft" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Altitude (ft)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ft",
     "query": "SELECT max(\"value\") FROM \"autogen\".\"ft\" WHERE (\"entity_id\"::tag = 'r1t_altitude')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id::tag", "operator": "=", "value": "r1t_altitude" }
     ]
    }
   ]
  },
  { "title": "Battery & Charging", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Battery Capacity",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Battery Capacity",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "kWh",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id::tag", "operator": "=", "value": "r1t_battery_capacity" }
     ]
    }
   ]
  },
  {
   "title": "Charging Limit",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "%",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      {
       "key": "entity_id::tag",
       "operator": "=",
       "value": "r1t_battery_state_of_charge_limit"
      }
     ]
    }
   ]
  },
  {
   "title": "Charging",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 8, "y": 23 },
   "targets": [
    {
     "alias": "Charging Speed (kWh)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "kW",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id::tag", "operator": "=", "value": "r1t_charging_speed" }
     ]
    },
    {
     "alias": "Charging Rate (mph)",
     "query": "SELECT last(\"value\") FROM \"mph\" WHERE (\"entity_id\"::tag = 'r1t_charging_rate') AND $timeFilter GROUP BY time($__interval) fill(previous)"
    },
    {
     "alias": "SoC",
     "query": "SELECT mean(\"value\") FROM \"autogen\".\"%\" WHERE (\"entity_id\"::tag = 'r1t_battery_state_of_charge') AND $timeFilter GROUP BY time($__interval) fill(previous)"
    }
   ]
  },
  {
   "title": "Efficiency History",
   "type": "timeseries",
   "description": "Tracks efficiency (miles per kWh) of drives. 0 or null values mean the vehicle didn't move in that time period where efficiency was calculated.",
   "gridPos": { "h": 7, "w": 20, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "mi/kWh" } },
   "targets": [
    {
     "alias": "R1T Efficiency",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "mi/kWh",
     "query": "SELECT top(\"value\", 1) FROM \"mi/kWh\" WHERE (\"entity_id\"::tag = 'rivian_efficiency') AND $timeFilter GROUP BY time($__interval) fill(previous)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [
         3
        ],
        "type": "top"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id::tag", "operator": "=", "value": "rivian_efficiency" }
     ]
    }
   ]
  },
  {
   "title": "Vampire Drain (WIP)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 20, "x": 0, "y": 37 },
   "targets": [
    {
     "alias": "range drop",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "miles",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id::tag", "operator": "=", "value": "ev_vampire_drain_miles_lost" }
     ]
    },
    {
     "alias": "energy drop",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "kWh",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id::tag", "operator": "=", "value": "ev_vampire_drain_kwh_lost" }
     ]
    }
   ]
  },
  {
   "title": "WIP/Misc",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 },
   "collapsed": true,
   "panels": [
    {
     "title": "Panel Title",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "SELECT last(\"value\"), first(\"value\")\nFROM \"mi\"\nWHERE (\"entity_id\" = 'r1t_odometer') AND $timeFilter"
      },
      { "expression": "($__to - $__from) / 86400000", "type": "math" }
     ]
    }
   ]
  }
 ]
}